In [1]:
import pandas as pd 
import numpy as np 
from sklearn.preprocessing import OneHotEncoder
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.metrics import classification_report,accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

In [2]:
df=pd.read_csv(r"C:\Users\rajan\OneDrive\Desktop\CampusX\FastAPI\Insurance_premium\insurance.csv")

In [3]:
df.head()

   age  weight  height  income_lpa  smoker     city  occupation insurance_premium_category
0   67   119.8    1.56        2.92   False   Jaipur     retired                       High
1   36   101.1    1.83       34.28   False  Chennai  freelancer                        Low
2   39    56.8    1.64       36.64   False   Indore  freelancer                        Low
3   22   109.4    1.55        3.34    True   Mumbai     student                     Medium
4   69    62.2    1.60        3.94    True   Indore     retired                       High

In [4]:
df.shape

(100, 8)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 8 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   age                         100 non-null    int64
 1   weight                      100 non-null    float64
 2   height                      100 non-null    float64
 3   income_lpa                  100 non-null    float64
 4   smoker                      100 non-null    bool
 5   city                        100 non-null    object
 6   occupation                  100 non-null    object
 7   insurance_premium_category  100 non-null    object
dtypes: bool(1), float64(3), int64(1), object(3)
memory usage: 5.7+ KB

In [6]:
df.describe()

              age      weight      height  income_lpa
count  100.000000  100.000000  100.000000  100.000000
mean    47.180000   83.894000    1.713200   18.400600
std     16.649312   21.020278    0.110205   16.067465
min     18.000000   51.100000    1.500000    0.530000
25%     34.750000   63.650000    1.610000    2.897500
50%     47.000000   82.300000    1.730000   14.122583
75%     61.000000  101.300000    1.810000   30.162500
max     75.000000  119.800000    1.900000   50.000000

In [7]:
df_feat= df.copy()

In [8]:
# Feature 1:BMI 
df_feat['bmi']= df_feat['weight'] / (df_feat['height']**2)

In [10]:
# Feat 2 Age Group 
def age_group(age):
    if age <25:
        return "young" 
    elif age <45:
        return "adult" 
    elif age <60:
        return "middle_ages"
    return "senior"

In [11]:
df_feat["age_group"] = df_feat["age"].apply(age_group)

In [12]:
# Feature 3: Lifestyle Risk
def lifestyle_risk(row):
    if row["smoker"] and row["bmi"] > 30:
        return "high"
    elif row["smoker"] or row["bmi"] > 27:
        return "medium"
    else:
        return "low"

In [13]:
df_feat["lifestyle_risk"] = df_feat.apply(lifestyle_risk, axis=1)

In [14]:
tier_1_cities = ["Mumbai", "Delhi", "Bangalore", "Chennai", "Kolkata", "Hyderabad", "Pune"]
tier_2_cities = [
    "Jaipur", "Chandigarh", "Indore", "Lucknow", "Patna", "Ranchi", "Visakhapatnam", "Coimbatore",
    "Bhopal", "Nagpur", "Vadodara", "Surat", "Rajkot", "Jodhpur", "Raipur", "Amritsar", "Varanasi",
    "Agra", "Dehradun", "Mysore", "Jabalpur", "Guwahati", "Thiruvananthapuram", "Ludhiana", "Nashik",
    "Allahabad", "Udaipur", "Aurangabad", "Hubli", "Belgaum", "Salem", "Vijayawada", "Tiruchirappalli",
    "Bhavnagar", "Gwalior", "Dhanbad", "Bareilly", "Aligarh", "Gaya", "Kozhikode", "Warangal",
    "Kolhapur", "Bilaspur", "Jalandhar", "Noida", "Guntur", "Asansol", "Siliguri"
]

In [15]:
# Feature 4: City Tier
def city_tier(city):
    if city in tier_1_cities:
        return 1
    elif city in tier_2_cities:
        return 2
    else:
        return 3

In [16]:
df_feat["city_tier"] = df_feat["city"].apply(city_tier)

In [17]:
df_feat.drop(columns=['age', 'weight', 'height', 'smoker', 'city'])[['income_lpa', 'occupation', 'bmi', 'age_group', 'lifestyle_risk', 'city_tier', 'insurance_premium_category']].sample(5)

    income_lpa      occupation        bmi    age_group lifestyle_risk  city_tier insurance_premium_category
27    34.33000     private_job  35.159702  middle_ages         medium          2                     Medium
99    28.16664  government_job  27.688778        adult         medium          1                        Low
95    19.64000  business_owner  21.420747        adult            low          2                        Low
34     0.68000         retired  32.914286       senior           high          3                       High
36     0.53000         retired  21.713266       senior            low          1                     Medium

In [19]:
# Select features and target
X = df_feat[["bmi", "age_group", "lifestyle_risk", "city_tier", "income_lpa", "occupation"]]
y = df_feat["insurance_premium_category"]

In [20]:
X

          bmi    age_group lifestyle_risk  city_tier  income_lpa      occupation
0   49.227482       senior         medium          2     2.92000         retired
1   30.189017        adult         medium          1    34.28000      freelancer
2   21.118382        adult            low          2    36.64000      freelancer
3   45.535900        young           high          1     3.34000         student
4   24.296875       senior         medium          2     3.94000         retired
..        ...          ...            ...        ...         ...             ...
95  21.420747        adult            low          2    19.64000  business_owner
96  47.984483        adult         medium          1    34.01000     private_job
97  18.765432  middle_ages            low          1    44.86000      freelancer
98  30.521676        adult         medium          1    28.30000  business_owner
99  27.688778        adult         medium          1    28.16664  government_job

[100 rows x 6 columns]

In [21]:
y

0       High
1        Low
2        Low
3     Medium
4       High
       ...
95       Low
96       Low
97       Low
98       Low
99       Low
Name: insurance_premium_category, Length: 100, dtype: object

In [22]:
# Define categorical and numeric features
categorical_features = ["age_group", "lifestyle_risk", "occupation", "city_tier"]
numeric_features = ["bmi", "income_lpa"]

In [26]:
# Create column transformer for OHE
preprocessor = ColumnTransformer(
    transformers=[
        ("cat", OneHotEncoder(), categorical_features),
        ("num", "passthrough", numeric_features)
    ])

In [27]:
# Create a pipeline with preprocessing and random forest classifier
pipeline = Pipeline(steps=[
    ("preprocessor", preprocessor),
    ("classifier", RandomForestClassifier(random_state=42))
])

In [28]:
# Split data and train model
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)
pipeline.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('cat', OneHotEncoder(),
                                                  ['age_group',
                                                   'lifestyle_risk',
                                                   'occupation', 'city_tier']),
                                                 ('num', 'passthrough',
                                                  ['bmi', 'income_lpa'])])),
                ('classifier', RandomForestClassifier(random_state=42))])

In [29]:
# Predict and evaluate
y_pred = pipeline.predict(X_test)
accuracy_score(y_test, y_pred)

0.9

In [30]:
X_test.sample(5)

          bmi    age_group lifestyle_risk  city_tier  income_lpa   occupation
44  30.078125  middle_ages           high          2       50.00  private_job
78  27.932798  middle_ages         medium          2       14.74   freelancer
36  21.713266       senior            low          1        0.53      retired
81  31.866055        adult           high          2       22.19   freelancer
39  35.643424  middle_ages           high          1       11.99   unemployed

In [32]:
import pickle

# Save the trained pipeline using pickle
pickle_model_path = "model.pkl"
with open(pickle_model_path, "wb") as f:
    pickle.dump(pipeline, f)